//! @generated by jedem for the `python` target. Do not edit.
//!
//! Surface `jawohl` v0.2.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

/// A core error surfaces as a Python exception carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}

/// A handle is empty only between a builder taking its value out and putting
/// it back, so seeing this means that builder panicked. The handle cannot be
/// repaired -- Rust consumed the value -- so every later call says so.
const EMPTIED: &str = "this handle was emptied by a builder that panicked";
/// How numeric prefixes are read.
///
/// The sharpest problem in the design. `"limit": 1000` against `maximum: 100`
/// looks like an obvious early cancel — but `1000` may still become `1000e-9`,
/// which is `0.000001`, and the `e` need not come next (`1000.5e-9` is legal
/// too). Under exact analysis **no numeric bound is ever decidable before the
/// number is delimited**, which deletes the feature entirely.
///
/// So the assumption is made explicit, and enforced.
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum NumberProfile {
    PlainDecimal,
    Exact,
}

impl From<jawohl::NumberProfile> for NumberProfile {
    fn from(v: jawohl::NumberProfile) -> Self {
        match v {
            jawohl::NumberProfile::PlainDecimal => Self::PlainDecimal,
            jawohl::NumberProfile::Exact => Self::Exact,
        }
    }
}

impl From<NumberProfile> for jawohl::NumberProfile {
    fn from(v: NumberProfile) -> Self {
        match v {
            NumberProfile::PlainDecimal => Self::PlainDecimal,
            NumberProfile::Exact => Self::Exact,
        }
    }
}

/// What is known about a value's validity.
///
/// The two "so far" states are what make this different from a batch
/// validator, and [`IrrecoverablyInvalid`](Validation::IrrecoverablyInvalid) is
/// the one that pays for itself: it means no continuation of the input can make
/// this value valid, so the caller may stop now.
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Validation {
    Pending,
    ValidSoFar,
    Valid,
    Invalid,
    IrrecoverablyInvalid,
}

impl From<jawohl::Validation> for Validation {
    fn from(v: jawohl::Validation) -> Self {
        match v {
            jawohl::Validation::Pending => Self::Pending,
            jawohl::Validation::ValidSoFar => Self::ValidSoFar,
            jawohl::Validation::Valid => Self::Valid,
            jawohl::Validation::Invalid => Self::Invalid,
            jawohl::Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

impl From<Validation> for jawohl::Validation {
    fn from(v: Validation) -> Self {
        match v {
            Validation::Pending => Self::Pending,
            Validation::ValidSoFar => Self::ValidSoFar,
            Validation::Valid => Self::Valid,
            Validation::Invalid => Self::Invalid,
            Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

/// How far along a value is, syntactically.
///
/// Orthogonal to validation state (see `Validation`, added in the validation
/// layer). `Missing` is distinct from `Incomplete`: a key that has not appeared
/// at all is missing, whereas one whose value is half-written is incomplete.
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Syntax {
    Missing,
    Incomplete,
    Complete,
}

impl From<jawohl::Syntax> for Syntax {
    fn from(v: jawohl::Syntax) -> Self {
        match v {
            jawohl::Syntax::Missing => Self::Missing,
            jawohl::Syntax::Incomplete => Self::Incomplete,
            jawohl::Syntax::Complete => Self::Complete,
        }
    }
}

impl From<Syntax> for jawohl::Syntax {
    fn from(v: Syntax) -> Self {
        match v {
            Syntax::Missing => Self::Missing,
            Syntax::Incomplete => Self::Incomplete,
            Syntax::Complete => Self::Complete,
        }
    }
}

// ---- Stream ----

#[pyclass]
pub struct Stream {
    inner: Option<jawohl::Stream>,
}

impl From<jawohl::Stream> for Stream {
    fn from(inner: jawohl::Stream) -> Self {
        Self { inner: Some(inner) }
    }
}

#[pymethods]
impl Stream {
    #[new]
    fn new() -> Self {
        jawohl::Stream::new().into()
    }

    /// A stream that validates against a JSON Schema as it parses.
    ///
    /// Uses [`NumberProfile::PlainDecimal`], which is what makes numeric
    /// bounds decidable on a partial value — see
    /// [`with_number_profile`](Stream::with_number_profile) for the trade.
    ///
    /// ```
    /// # use jawohl::{Stream, Validation};
    /// let mut s = Stream::from_json_schema(r#"{"properties":{"role":{"enum":["user","admin"]}}}"#).unwrap();
    /// s.push(br#"{"role":"sup"#).unwrap();
    /// // No member begins "sup", and none ever will.
    /// assert_eq!(s.validation("/role"), Validation::IrrecoverablyInvalid);
    /// assert!(s.is_irrecoverable());
    /// ```
    ///
    /// # Errors
    ///
    /// If the schema is not valid JSON, is not a schema, or contains a `$ref`
    /// that does not resolve. Keywords that merely cannot be *lowered* are not
    /// errors — they are recorded in [`lowering_report`](Stream::lowering_report).
    #[staticmethod]
    fn from_json_schema(schema: &str) -> PyResult<Self> {
        Ok(jawohl::Stream::from_json_schema(schema).map_err(err)?.into())
    }

    /// Choose how numeric prefixes are read.
    ///
    /// [`NumberProfile::PlainDecimal`] (the default) lets `"limit": 1000` be
    /// rejected against `maximum: 100` before the number is delimited, and
    /// fails the stream if an exponent ever appears. [`NumberProfile::Exact`]
    /// accepts every JSON number and gives up early numeric rejection, because
    /// `1000` may still become `1000e-9`.
    ///
    /// No effect without a schema: with nothing to judge there is nothing to
    /// be unsound about, and `1e10` is simply a number.
    fn with_number_profile(mut slf: PyRefMut<'_, Self>, profile: NumberProfile) -> PyRefMut<'_, Self> {
        let inner = slf.inner.take().expect(EMPTIED);
        slf.inner = Some(inner.with_number_profile(profile.into()));
        slf
    }

    /// How the value at `pointer` stands against the schema.
    ///
    /// [`Validation::Pending`] without a schema, or where the schema says
    /// nothing about that path.
    fn validation(&self, pointer: &str) -> Validation {
        self.get().validation(pointer).into()
    }

    /// True when the document can no longer become valid, whatever arrives.
    ///
    /// The early-cancellation signal: a caller seeing this can stop the
    /// generation producing the input rather than paying for the rest of it.
    fn is_irrecoverable(&self) -> bool {
        self.get().is_irrecoverable()
    }

    /// Set the maximum container nesting depth. The default is
    /// [`DEFAULT_MAX_DEPTH`].
    ///
    /// Nesting deeper than this is a [`ParseErrorKind::DepthLimitExceeded`].
    /// The limit exists because jawohl's input is untrusted model output and
    /// every level costs an allocation: without a ceiling, `[` repeated is a
    /// denial-of-service vector. Raise it if you genuinely have deep
    /// documents; lower it to harden further.
    ///
    /// ```
    /// # use jawohl::Stream;
    /// let mut s = Stream::new().with_max_depth(3);
    /// assert!(s.push(b"[[[[[1]]]]]").is_err());
    /// ```
    fn with_max_depth(mut slf: PyRefMut<'_, Self>, depth: i64) -> PyRefMut<'_, Self> {
        let inner = slf.inner.take().expect(EMPTIED);
        slf.inner = Some(inner.with_max_depth(depth as usize));
        slf
    }

    /// Feed the next chunk.
    ///
    /// Returns `Err` only if the input cannot be a prefix of any valid JSON
    /// document. Running out of input mid-value is not an error — it is the
    /// normal state of a stream. Once a stream has failed it stays failed.
    fn push(&mut self, chunk: &[u8]) -> PyResult<()> {
        self.get_mut().push(chunk).map_err(err)?;
        Ok(())
    }

    /// How far along the value at `pointer` is.
    ///
    /// `pointer` is an RFC 6901 JSON Pointer: `""` is the root, `/query` a
    /// member, `/messages/0/role` a nested one.
    fn status(&self, pointer: &str) -> Syntax {
        self.get().status(pointer).into()
    }

    /// True once the root value has closed.
    fn is_document_complete(&self) -> bool {
        self.get().is_document_complete()
    }

    /// Signal end of input: completes a trailing number or literal if it is
    /// well-formed. Containers left open simply stay open.
    fn finish(&mut self) -> PyResult<()> {
        self.get_mut().finish().map_err(err)?;
        Ok(())
    }
}
impl Stream {
    fn get(&self) -> &jawohl::Stream {
        self.inner.as_ref().expect(EMPTIED)
    }
    fn get_mut(&mut self) -> &mut jawohl::Stream {
        self.inner.as_mut().expect(EMPTIED)
    }
}

// ---- complete_json ----

/// Complete a truncated JSON document so that it parses.
///
/// This is jawohl's original entry point, now built on the incremental parser
/// and therefore correct on inputs the bracket-counting version silently
/// corrupted — a dangling `\`, a half-written `\uXXXX`, a partial literal, a
/// key with no value, a trailing comma.
///
/// Anything not yet complete enough to be valid is **dropped**, and anything
/// unambiguously completable is **finished**: `tru` becomes `true`, an open
/// string is closed after its stable prefix.
///
/// ```
/// # use jawohl::complete_json;
/// assert_eq!(
/// complete_json(r#"{"key":"value","arr":[1,2,{"nested":"v"#).unwrap(),
/// r#"{"key":"value","arr":[1,2,{"nested":"v"}]}"#
/// );
/// // a dangling escape is dropped rather than escaping the closing quote
/// assert_eq!(complete_json(r#"{"a":"x\"#).unwrap(), r#"{"a":"x"}"#);
/// // a partial literal is finished
/// assert_eq!(complete_json(r#"{"a":tru"#).unwrap(), r#"{"a":true}"#);
/// ```
///
/// # Errors
///
/// Returns `Err` if the input is not a prefix of any valid JSON document.
/// Unlike 1.0, which returned `Ok` with invalid output, a malformed input is
/// reported as such.
///
/// # A note on numbers
///
/// A trailing undelimited number is emitted as-is (`{"limit":10` completes to
/// `{"limit":10}`), because that is what a display consumer wants. It is
/// therefore the one part of the output that a later chunk may change — use
/// [`Stream::status`] if you need the stability guarantee.
#[pyfunction]
pub fn complete_json(input: &str) -> PyResult<String> {
    jawohl::complete_json(input).map_err(err)
}

// ---- get_closing_string_for_partial_json ----

/// The closing string 1.0 would have appended — kept for source compatibility.
///
/// Prefer [`complete_json`]: because 2.0 may need to *drop* an incomplete
/// fragment rather than append to it, a suffix alone cannot always express the
/// completion. This returns the suffix when one exists, and an empty string
/// when the completion required dropping something.
#[pyfunction]
pub fn get_closing_string_for_partial_json(input: &str) -> PyResult<String> {
    jawohl::get_closing_string_for_partial_json(input).map_err(err)
}

/// Register everything on the module. Call this from your `#[pymodule]`.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<NumberProfile>()?;
    m.add_class::<Validation>()?;
    m.add_class::<Syntax>()?;
    m.add_class::<Stream>()?;
    m.add_function(wrap_pyfunction!(complete_json, m)?)?;
    m.add_function(wrap_pyfunction!(get_closing_string_for_partial_json, m)?)?;
    Ok(())
}
