//! GENERATED by jedem for the `python` target. Do not edit.
//!
//! Surface `jawohl` v0.2.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.

#![allow(clippy::all)]
#![allow(unused_imports)]

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

/// A core error surfaces as a Python exception carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}

// ---- Jawohl ----

/// Complete a truncated JSON document so that it parses.
///
/// Raises if the input is not a prefix of any valid JSON document.
#[pyfunction]
pub fn complete_json(input: &str) -> PyResult<String> {
    jawohl_surface::Jawohl::complete_json(input).map_err(err)
}

/// Is this a prefix of some valid JSON document?
#[pyfunction]
pub fn is_valid_prefix(input: &str) -> bool {
    jawohl_surface::Jawohl::is_valid_prefix(input)
}

/// Has the document finished?
#[pyfunction]
pub fn is_complete(input: &str) -> PyResult<bool> {
    jawohl_surface::Jawohl::is_complete(input).map_err(err)
}

/// How far along the value at `pointer` is: `missing`, `incomplete` or
/// `complete`.
///
/// `complete` carries the stability guarantee — that value will not change,
/// so it is safe to act on.
#[pyfunction]
pub fn status(input: &str, pointer: &str) -> PyResult<String> {
    jawohl_surface::Jawohl::status(input, pointer).map_err(err)
}

/// The value at `pointer`, but only once it is final. Absent while it can
/// still change.
#[pyfunction]
pub fn settled_value(input: &str, pointer: &str) -> PyResult<Option<String>> {
    jawohl_surface::Jawohl::settled_value(input, pointer).map_err(err)
}

/// Validate what has arrived against a JSON Schema, returning one of
/// `pending`, `valid_so_far`, `valid`, `invalid`, `irrecoverably_invalid`.
#[pyfunction]
pub fn validate(schema: &str, input: &str, pointer: &str) -> PyResult<String> {
    jawohl_surface::Jawohl::validate(schema, input, pointer).map_err(err)
}

/// **Can this generation still succeed?**
///
/// `true` means no continuation of the input can satisfy the schema, so a
/// caller should stop generating. This is the one function worth crossing a
/// language boundary for.
#[pyfunction]
pub fn is_irrecoverable(schema: &str, input: &str) -> PyResult<bool> {
    jawohl_surface::Jawohl::is_irrecoverable(schema, input).map_err(err)
}

/// Which schema constraints jawohl could not lower, and why. Empty when
/// everything compiled.
#[pyfunction]
pub fn lowering_report(schema: &str) -> PyResult<String> {
    jawohl_surface::Jawohl::lowering_report(schema).map_err(err)
}

/// Register everything on the module. Call this from your `#[pymodule]`.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(complete_json, m)?)?;
    m.add_function(wrap_pyfunction!(is_valid_prefix, m)?)?;
    m.add_function(wrap_pyfunction!(is_complete, m)?)?;
    m.add_function(wrap_pyfunction!(status, m)?)?;
    m.add_function(wrap_pyfunction!(settled_value, m)?)?;
    m.add_function(wrap_pyfunction!(validate, m)?)?;
    m.add_function(wrap_pyfunction!(is_irrecoverable, m)?)?;
    m.add_function(wrap_pyfunction!(lowering_report, m)?)?;
    Ok(())
}
