//! @generated by jedem for the `python` target. Do not edit.
//!
//! Surface `jawohl` v0.2.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

/// A core error surfaces as a Python exception carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}
/// How far along a value is.
///
/// A mirror of [`jawohl::Syntax`], because `#[derive(jedem::Enum)]` has to be
/// applied where the type is defined and jawohl itself takes no dependency on
/// jedem. The cost is one `From` impl; the gain is that Python receives a real
/// enum member and TypeScript a string-literal union, rather than a bare string
/// only convention keeps correct.
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Syntax {
    Missing,
    Incomplete,
    Complete,
}

impl From<jawohl_surface::Syntax> for Syntax {
    fn from(v: jawohl_surface::Syntax) -> Self {
        match v {
            jawohl_surface::Syntax::Missing => Self::Missing,
            jawohl_surface::Syntax::Incomplete => Self::Incomplete,
            jawohl_surface::Syntax::Complete => Self::Complete,
        }
    }
}

impl From<Syntax> for jawohl_surface::Syntax {
    fn from(v: Syntax) -> Self {
        match v {
            Syntax::Missing => Self::Missing,
            Syntax::Incomplete => Self::Incomplete,
            Syntax::Complete => Self::Complete,
        }
    }
}

/// What is known about a value's validity.
///
/// A mirror of [`jawohl::Validation`], for the same reason as [`Syntax`].
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Validation {
    Pending,
    ValidSoFar,
    Valid,
    Invalid,
    IrrecoverablyInvalid,
}

impl From<jawohl_surface::Validation> for Validation {
    fn from(v: jawohl_surface::Validation) -> Self {
        match v {
            jawohl_surface::Validation::Pending => Self::Pending,
            jawohl_surface::Validation::ValidSoFar => Self::ValidSoFar,
            jawohl_surface::Validation::Valid => Self::Valid,
            jawohl_surface::Validation::Invalid => Self::Invalid,
            jawohl_surface::Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

impl From<Validation> for jawohl_surface::Validation {
    fn from(v: Validation) -> Self {
        match v {
            Validation::Pending => Self::Pending,
            Validation::ValidSoFar => Self::ValidSoFar,
            Validation::Valid => Self::Valid,
            Validation::Invalid => Self::Invalid,
            Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

// ---- jawohl_api ----

/// Complete a truncated JSON document so that it parses.
///
/// Fails if the input is not a prefix of any valid JSON document.
#[pyfunction]
pub fn complete_json(input: &str) -> PyResult<String> {
    jawohl_surface::jawohl_api::complete_json(input).map_err(err)
}

/// Is this a prefix of some valid JSON document?
#[pyfunction]
pub fn is_valid_prefix(input: &str) -> bool {
    jawohl_surface::jawohl_api::is_valid_prefix(input)
}

/// Has the document finished?
#[pyfunction]
pub fn is_complete(input: &str) -> PyResult<bool> {
    jawohl_surface::jawohl_api::is_complete(input).map_err(err)
}

/// How far along the value at `pointer` is.
///
/// [`Syntax::Complete`] carries the stability guarantee: that value will
/// not change, so it is safe to act on.
#[pyfunction]
pub fn status(input: &str, pointer: &str) -> PyResult<Syntax> {
    jawohl_surface::jawohl_api::status(input, pointer).map(|v| v.into()).map_err(err)
}

/// The completed document, but only once the value at `pointer` is final.
/// Absent while it can still change.
#[pyfunction]
pub fn settled(input: &str, pointer: &str) -> PyResult<Option<String>> {
    jawohl_surface::jawohl_api::settled(input, pointer).map_err(err)
}

/// Validate what has arrived against a JSON Schema.
#[pyfunction]
pub fn validate(schema: &str, input: &str, pointer: &str) -> PyResult<Validation> {
    jawohl_surface::jawohl_api::validate(schema, input, pointer).map(|v| v.into()).map_err(err)
}

/// **Can this generation still succeed?**
///
/// `true` means no continuation of the input can satisfy the schema, so a
/// caller should stop generating. This is the one function worth crossing a
/// language boundary for.
#[pyfunction]
pub fn is_irrecoverable(schema: &str, input: &str) -> PyResult<bool> {
    jawohl_surface::jawohl_api::is_irrecoverable(schema, input).map_err(err)
}

/// Which schema constraints jawohl could not lower, and why. Empty when
/// everything compiled.
#[pyfunction]
pub fn lowering_report(schema: &str) -> PyResult<String> {
    jawohl_surface::jawohl_api::lowering_report(schema).map_err(err)
}

/// Register everything on the module. Call this from your `#[pymodule]`.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Syntax>()?;
    m.add_class::<Validation>()?;
    m.add_function(wrap_pyfunction!(complete_json, m)?)?;
    m.add_function(wrap_pyfunction!(is_valid_prefix, m)?)?;
    m.add_function(wrap_pyfunction!(is_complete, m)?)?;
    m.add_function(wrap_pyfunction!(status, m)?)?;
    m.add_function(wrap_pyfunction!(settled, m)?)?;
    m.add_function(wrap_pyfunction!(validate, m)?)?;
    m.add_function(wrap_pyfunction!(is_irrecoverable, m)?)?;
    m.add_function(wrap_pyfunction!(lowering_report, m)?)?;
    Ok(())
}
