// @generated by jedem for the `python` target. Do not edit.
// Surface `jawohl` v0.2.0. Regenerate with `cargo jedem generate`.

mod generated;

#[pyo3::pymodule]
fn jawohl(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {
    generated::register(m)
}
