//! @generated by jedem for the `node` target. Do not edit.
//!
//! Surface `jawohl` v0.2.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]
// napi registers each function at module load, so nothing in this crate
// references them by name and rustc cannot tell they are used.
#![allow(dead_code)]

use napi_derive::napi;

/// A core error surfaces as a thrown JS `Error` carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}
/// What is known about a value's validity.
///
/// The two "so far" states are what make this different from a batch
/// validator, and [`IrrecoverablyInvalid`](Validation::IrrecoverablyInvalid) is
/// the one that pays for itself: it means no continuation of the input can make
/// this value valid, so the caller may stop now.
#[napi(string_enum)]
pub enum Validation {
    Pending,
    ValidSoFar,
    Valid,
    Invalid,
    IrrecoverablyInvalid,
}

impl From<jawohl::Validation> for Validation {
    fn from(v: jawohl::Validation) -> Self {
        match v {
            jawohl::Validation::Pending => Self::Pending,
            jawohl::Validation::ValidSoFar => Self::ValidSoFar,
            jawohl::Validation::Valid => Self::Valid,
            jawohl::Validation::Invalid => Self::Invalid,
            jawohl::Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

impl From<Validation> for jawohl::Validation {
    fn from(v: Validation) -> Self {
        match v {
            Validation::Pending => Self::Pending,
            Validation::ValidSoFar => Self::ValidSoFar,
            Validation::Valid => Self::Valid,
            Validation::Invalid => Self::Invalid,
            Validation::IrrecoverablyInvalid => Self::IrrecoverablyInvalid,
        }
    }
}

/// How far along a value is, syntactically.
///
/// Orthogonal to validation state (see `Validation`, added in the validation
/// layer). `Missing` is distinct from `Incomplete`: a key that has not appeared
/// at all is missing, whereas one whose value is half-written is incomplete.
#[napi(string_enum)]
pub enum Syntax {
    Missing,
    Incomplete,
    Complete,
}

impl From<jawohl::Syntax> for Syntax {
    fn from(v: jawohl::Syntax) -> Self {
        match v {
            jawohl::Syntax::Missing => Self::Missing,
            jawohl::Syntax::Incomplete => Self::Incomplete,
            jawohl::Syntax::Complete => Self::Complete,
        }
    }
}

impl From<Syntax> for jawohl::Syntax {
    fn from(v: Syntax) -> Self {
        match v {
            Syntax::Missing => Self::Missing,
            Syntax::Incomplete => Self::Incomplete,
            Syntax::Complete => Self::Complete,
        }
    }
}

// ---- Stream ----

#[napi]
pub struct Stream {
    inner: jawohl::Stream,
}

impl From<jawohl::Stream> for Stream {
    fn from(inner: jawohl::Stream) -> Self {
        Self { inner }
    }
}

#[napi]
impl Stream {
    #[napi(constructor)]
    pub fn new() -> Self {
        jawohl::Stream::new().into()
    }

    /// A stream that validates against a JSON Schema as it parses.
    ///
    /// Uses [`NumberProfile::PlainDecimal`], which is what makes numeric
    /// bounds decidable on a partial value — see
    /// [`with_number_profile`](Stream::with_number_profile) for the trade.
    ///
    /// ```
    /// # use jawohl::{Stream, Validation};
    /// let mut s = Stream::from_json_schema(r#"{"properties":{"role":{"enum":["user","admin"]}}}"#).unwrap();
    /// s.push(br#"{"role":"sup"#).unwrap();
    /// // No member begins "sup", and none ever will.
    /// assert_eq!(s.validation("/role"), Validation::IrrecoverablyInvalid);
    /// assert!(s.is_irrecoverable());
    /// ```
    ///
    /// # Errors
    ///
    /// If the schema is not valid JSON, is not a schema, or contains a `$ref`
    /// that does not resolve. Keywords that merely cannot be *lowered* are not
    /// errors — they are recorded in [`lowering_report`](Stream::lowering_report).
    #[napi(factory, js_name = "fromJsonSchema")]
    pub fn from_json_schema(schema: String) -> napi::Result<Self> {
        Ok(jawohl::Stream::from_json_schema(&schema).map_err(err)?.into())
    }

    /// How the value at `pointer` stands against the schema.
    ///
    /// [`Validation::Pending`] without a schema, or where the schema says
    /// nothing about that path.
    #[napi(js_name = "validation")]
    pub fn validation(&self, pointer: String) -> Validation {
        self.inner.validation(&pointer).into()
    }

    /// True when the document can no longer become valid, whatever arrives.
    ///
    /// The early-cancellation signal: a caller seeing this can stop the
    /// generation producing the input rather than paying for the rest of it.
    #[napi(js_name = "isIrrecoverable")]
    pub fn is_irrecoverable(&self) -> bool {
        self.inner.is_irrecoverable()
    }

    /// Feed the next chunk.
    ///
    /// Returns `Err` only if the input cannot be a prefix of any valid JSON
    /// document. Running out of input mid-value is not an error — it is the
    /// normal state of a stream. Once a stream has failed it stays failed.
    #[napi(js_name = "push")]
    pub fn push(&mut self, chunk: napi::bindgen_prelude::Uint8Array) -> napi::Result<()> {
        self.inner.push(&chunk).map_err(err)?;
        Ok(())
    }

    /// How far along the value at `pointer` is.
    ///
    /// `pointer` is an RFC 6901 JSON Pointer: `""` is the root, `/query` a
    /// member, `/messages/0/role` a nested one.
    #[napi(js_name = "status")]
    pub fn status(&self, pointer: String) -> Syntax {
        self.inner.status(&pointer).into()
    }

    /// True once the root value has closed.
    #[napi(js_name = "isDocumentComplete")]
    pub fn is_document_complete(&self) -> bool {
        self.inner.is_document_complete()
    }

    /// Signal end of input: completes a trailing number or literal if it is
    /// well-formed. Containers left open simply stay open.
    #[napi(js_name = "finish")]
    pub fn finish(&mut self) -> napi::Result<()> {
        self.inner.finish().map_err(err)?;
        Ok(())
    }
}

// ---- complete_json ----

/// Complete a truncated JSON document so that it parses.
///
/// This is jawohl's original entry point, now built on the incremental parser
/// and therefore correct on inputs the bracket-counting version silently
/// corrupted — a dangling `\`, a half-written `\uXXXX`, a partial literal, a
/// key with no value, a trailing comma.
///
/// Anything not yet complete enough to be valid is **dropped**, and anything
/// unambiguously completable is **finished**: `tru` becomes `true`, an open
/// string is closed after its stable prefix.
///
/// ```
/// # use jawohl::complete_json;
/// assert_eq!(
/// complete_json(r#"{"key":"value","arr":[1,2,{"nested":"v"#).unwrap(),
/// r#"{"key":"value","arr":[1,2,{"nested":"v"}]}"#
/// );
/// // a dangling escape is dropped rather than escaping the closing quote
/// assert_eq!(complete_json(r#"{"a":"x\"#).unwrap(), r#"{"a":"x"}"#);
/// // a partial literal is finished
/// assert_eq!(complete_json(r#"{"a":tru"#).unwrap(), r#"{"a":true}"#);
/// ```
///
/// # Errors
///
/// Returns `Err` if the input is not a prefix of any valid JSON document.
/// Unlike 1.0, which returned `Ok` with invalid output, a malformed input is
/// reported as such.
///
/// # A note on numbers
///
/// A trailing undelimited number is emitted as-is (`{"limit":10` completes to
/// `{"limit":10}`), because that is what a display consumer wants. It is
/// therefore the one part of the output that a later chunk may change — use
/// [`Stream::status`] if you need the stability guarantee.
#[napi(js_name = "completeJson")]
pub fn complete_json(input: String) -> napi::Result<String> {
    jawohl::complete_json(&input).map_err(err)
}

// ---- get_closing_string_for_partial_json ----

/// The closing string 1.0 would have appended — kept for source compatibility.
///
/// Prefer [`complete_json`]: because 2.0 may need to *drop* an incomplete
/// fragment rather than append to it, a suffix alone cannot always express the
/// completion. This returns the suffix when one exists, and an empty string
/// when the completion required dropping something.
#[napi(js_name = "getClosingStringForPartialJson")]
pub fn get_closing_string_for_partial_json(input: String) -> napi::Result<String> {
    jawohl::get_closing_string_for_partial_json(&input).map_err(err)
}
