// @generated by jedem for the `node` target. Do not edit.
// Surface `jawohl` v0.2.0. Regenerate with `cargo jedem generate`.

// napi registers each function at module load, so there is no
// module function to write.
mod generated;
